apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: 3tirewebapp-dev
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::326864272150:role/backend-irsa-...
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: 3tirewebapp-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: backend-sa
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials-from-sm
  namespace: 3tirewebapp-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres-credentials-from-kv
    creationPolicy: Owner
  data:
  - secretKey: POSTGRES_DB
    remoteRef:
      key: gitops-app-db-secrets
      property: POSTGRES_DB
  - secretKey: POSTGRES_USER
    remoteRef:
      key: gitops-app-db-secrets
      property: POSTGRES_USER
  - secretKey: POSTGRES_PASSWORD
    remoteRef:
      key: gitops-app-db-secrets
      property: POSTGRES_PASSWORD
